apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd

spec:
  project: default
  source:
    repoURL: https://github.com/sachinchaudhary-system-engineer/Nginx-app.git
    targetRevision: main
    path: nginx

  destination:
    server: https://172.31.13.172:6443
    namespace: nginx-apache-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true 

    syncOptions:
      - CreateNamespace=true